### ISSUE TITLE
Support for .tsx?

### ISSUE THREAD

**Issue by trevorsg** [phenomnomnominal/tsquery#20]
Right now the parser chokes on tsx syntax. Any plans to support this? Or is there some way to tell tsquery to allow tsx?

**Comment by phenomnomnominal** [comment]
Could you show me what you mean by "chokes"? A repro of some sort would be handy! I would have expected it to work on any `SourceFile`, by default it uses:

```
// Dependencies:
import { createSourceFile, ScriptTarget, SourceFile } from 'typescript';

export function createAST (text: string, fileName?: string): SourceFile {
    return createSourceFile(fileName || '', text, ScriptTarget.Latest, true);
}
```

But you could pass one in that was created externally too, eg:

```
import { createSourceFile, ScriptKind, ScriptTarget } from 'typescript';

const ast = createSourceFile('my-file.tsx', text, ScriptTarget.Latest, true, ScriptKind.TSX);
tsquery(ast, 'Foo Bar');
```

Does that work?

**Comment by trevorsg** [comment]
Hi, sorry I didn't include a repro. It seems like any TSX syntax will not work when the ast is queried.

    const contents = `function returnJsx() { return (<div></div>); }`;
    const ast = tsquery.ast(contents); 
    const nodes = tsquery(ast, "*"); 

Result:

    Error: Invalid regular expression: //div>); }/: Unmatched ')'
    Stack: SyntaxError: Invalid regular expression: //div>); }/: Unmatched ')'
    at new RegExp (<anonymous>)
    at Object._a.(anonymous function) (C:\Temp\tsquery\node_modules\@phenomnomnominal\tsquery\dist\src\traverse.js:22:85)
    at addProperties (C:\Temp\tsquery\node_modules\@phenomnomnominal\tsquery\dist\src\traverse.js:68:40)
    at traverse (C:\Temp\tsquery\node_modules\@phenomnomnominal\tsquery\dist\src\traverse.js:27:5)
    at C:\Temp\tsquery\node_modules\@phenomnomnominal\tsquery\dist\src\traverse.js:29:49
    at visitNode (C:\Temp\tsquery\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (C:\Temp\tsquery\node_modules\typescript\lib\typescript.js:14994:21)
    at NodeObject.forEachChild (C:\Temp\tsquery\node_modules\typescript\lib\typescript.js:106733:23)
    at traverse (C:\Temp\tsquery\node_modules\@phenomnomnominal\tsquery\dist\src\traverse.js:29:10)
    at C:\Temp\tsquery\node_modules\@phenomnomnominal\tsquery\dist\src\traverse.js:29:49

However, when I use createSourceFile directly and pass ScriptKind.TSX, it works correctly. Thanks for the workaround!

**Comment by phenomnomnominal** [comment]
Does the workaround seem flexible enough for you? Or would you rather see a formal API for setting the AST parse options?

**Comment by urish** [comment]
How about modifying `ast` to read something like:

```
export function createAST (text: string, fileName?: string): SourceFile {
    return createSourceFile(fileName || '', text, ScriptTarget.Latest, true, fileName && fileName.toLowerCase().endsWith('.tsx') ? ScriptKind.TSX : ScriptKind.TS);
}
```

**Comment by phenomnomnominal** [comment]
would there be any downside to just always using TSX?

**Comment by urish** [comment]
I have no idea. One thought I had it might affect the `<type>` cast syntax.

Perhaps @DanielRosenwasser or @mhegazy can comment on the differences when parsing as ScriptKind.TSX vs ScriptKind.TS ?

**Comment by DanielRosenwasser** [comment]
* Won't work at all on `<Foo>` assertion syntax (it will parse incorrectly)
* Currently the following doesn't parse in `.tsx` files: `<T>(x: T) => x`

Those are the two cases I know of.

**Comment by vogloblinsky** [comment]
Hi,
I am facing the same issue in a different context.
For a new developer tool coming in the next weeks, i use tsquery in the browser (builded with Browserify) to play with AST of TypeScript or JavaScript files.
My context is that i could have JSX code from a .tsx file or a .js file.
I will try to add a little jsx code detection in my codebase, but after that, i would need to way to tell to TSQuery any kinf of AST parse option.

So for me, adding a formal API could be enough, @phenomnomnominal what do you think about that ?

**Comment by vogloblinsky** [comment]
Yes, do you want a PR for that ?

**Comment by phenomnomnominal** [comment]
I'd love one, thank you!

**Comment by vogloblinsky** [comment]
> I'd love one, thank you!

And here it is : https://github.com/phenomnomnominal/tsquery/pull/35 :smile:
